# Local secrets for development
# This file should NOT be committed to git (add to .gitignore)

# Anthropic API Key for local development
ANTHROPIC_API_KEY = "your_anthropic_api_key_here"

# Alternative nested format (uncomment if preferred)
# [anthropic]
# api_key = "your_anthropic_api_key_here"
